spring:
  data:
    cassandra:
      keyspace-name: main
      username: ltrTGdcpJCBFTiIXigkEJDOE
      password: 3HrDP,IIT7H4TYIHZ__o2ITGhe3eT9Sg7TsqBJatQ8.czgbFAomZBIvw5LlZtKfp3Gg+Xa3EsLZN521XhFw0e_RQK7HhOeRsu7Wdh3saZfbtM8Few2Hu5XB0QoyRlcM4
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      schema-action: create_if_not_exists

datastax.astra:
  secure-connect-bundle: secure-connect-task.zip

astra.db:
  id: b046936d-4158-44f3-8677-c7a0d11cd96c-1
  region: europe-west1
  keyspace: main
  application.token: AstraCS:ltrTGdcpJCBFTiIXigkEJDOE:f0c2ca07d6adadef5f73b4d092a054a250570cb051e50ee9930d0d0c1da029f7

#logging:
#  config: /home/andrew/IdeaProjects/Task Server/src/main/resources/logback.xml

tasks:
  url-weapons: https://weapon-service-v1.herokuapp.com/api/v1/weapons/
  url-users: https://mafias-user-service-app.herokuapp.com/api/users/
  url-bands: https://heroku-bands.herokuapp.com/bands?bandName=

my:
  app:
    secret: AndrewReshetnyakAAAAAAAAAAAAAAAAaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa