spring:
  data:
    cassandra:
      keyspace-name: schema_db
      username: eaMLrrEtradaZNjqaCZLqvnc
      password: i8KNF-MuSe+7_IfTEX1s4nfZge4L,DgG7,zki_H3KQzRqRAS+onD,SvHCm-cglt8vMFQ6.0PxJiFJBna9dCd0Z7oogcpUq,DvpiY,anApK25+uhGcxQJ9NP-N8-MqIY0
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      schema-action: create_if_not_exists

datastax.astra:
  secure-connect-bundle: secure-connect-tasks-db (1).zip


astra.db:
  id: 70815b3c-23df-49d8-83b6-1fce4632359e-1
  region: europe-west1
  keyspace: schema_db
  application.token: AstraCS:eaMLrrEtradaZNjqaCZLqvnc:9f8432bc6ea72fe2d61c542a8f2278523aa1cf7de2504f102957be34a61afe15

